### ISSUE TITLE
pngout.exe has a trojan virus

### ISSUE THREAD

**Issue by dave-illini** [madskristensen/WebEssentials2013#1508]
The current version and a previous version of pngout.exe in this package are infected with a Trojan virus. 
Running F-secure Client Security 11.60 set to scan all & use heuristics, shows an alert for:
Gen:Trojan.Heur.FU.CMW@aW6FXOc
This web page from F-Secure describes it.
http://www.f-secure.com/v-descs/trojan-downloader_w32_heurfu_gen.shtml

Please fix this and alert the other nearly 500,000 people who have downloaded this tool.

WebEssentials2013\Resources\Tools\pngout.exe
5/14/2014 4:40 pm  38.0 KB
and
8/7/2014 4:24 pm  38.0 KB  
are the only versions I have & both were flagged by F-secure

**Comment by dotnetchris** [comment]
Reading #570 the virus name they claim "PAK_Generic.001" http://about-threats.trendmicro.com/us/malware/PAK_Generic.001 this is just pointless nagging. The author included compressed application code inside the binaries and the AV is freaking out because this tactic is sometimes employed by Malware peddlers.

This is like saying Murderers drive Cars, Cars are a Murderer tool! 

Just ignore this mindless FUD.

**Comment by Pckmule** [comment]
I've just got the latest updates for this tool and my company's AV (Trend Micro) is flagging it as a virus again... 

Reading through the earlier comments here, it doesn't sound like there is much that can be done, but surely it is possible to have the relevant DLLs white-listed by the major AV vendors?
