### ISSUE TITLE
Browser Link : The operation is insecure

### ISSUE THREAD

**Issue by koala59230** [madskristensen/WebEssentials2013#1712]
Hello,
When I try to use Browserlink in firefox developper edition last version or firefox 31 and >. In my browser console I have message : 

"La connexion avec ws://localhost:54821/d3029a943e5c4627b6cd2603afb8c7d7/arterySignalR/connect?transport=webSockets&connectionToken=AQAAANCMnd8BFdERjHoAwE%2FCl%2BsBAAAAQDl2BhJdJkqwr93YDyFxjgAAAAACAAAAAAADZgAAwAAAABAAAABUyWvau0KKJEB24DnXOFC6AAAAAASAAACgAAAAEAAAAEfse1tob8PAZLkL9lhW9x4oAAAAwOOU5Dq86ki8aCrzEBV15w5W5HuP17z%2FAuWAJRNsTaNxjHpgQXWSIxQAAADtEK%2BOyVS5F0mbNuIdl37%2BcGrT0g%3D%3D&requestUrl=http%3A%2F%2Flocalhost%3A55367%2F&browserName=Firefox&userAgent=Mozilla%2F5.0+(Windows+NT+6.3%3B+WOW64%3B+rv%3A36.0)+Gecko%2F20100101+Firefox%2F36.0&tid=0 a été interrompue pendant le chargement de la page. browserLink:62:0"

"aucun élément trouvé abort:1:1"

"[09:30:37 GMT+0100] Browser Link: Exception thrown in callback method setPixelPusingMode: SecurityError: The operation is insecure." browserLink:64:552"

"[09:30:37 GMT+0100] Browser Link: Failed to invoke return value callback:
SecurityError: The operation is insecure." browserLink:64:552"

Under IE, browserlink run with no problems.

- Visual Studio is 2013 Premium 12.0.31101.00 Update 4
- Web Essentials 2013 for Update 4 Version 2.5.3

Thanxs

**Comment by danofa** [comment]
Yup, I am getting similar errors, Web essentials runs with no problems in chrome and ie, but for some reason the menu is not displayed correctly - just the web essentials icon and the autohide checkbox, running Visual Studio 2013 w/ Web Essentials 2013 for Update 4 version 2.5.4


here is console output from firefox..

Unknown pseudo-class or pseudo-element '-webkit-inner-spin-button'.  Ruleset ignored due to bad selector. bootstrap.css:178:22
Unknown pseudo-class or pseudo-element '-webkit-search-cancel-button'.  Ruleset ignored due to bad selector. bootstrap.css:188:22
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. bootstrap.css:304:25
Expected color but found 'auto'.  Expected color but found '-webkit-focus-ring-color'.  Expected end of value but found '-webkit-focus-ring-color'.  Error in parsing value for 'outline'.  Declaration dropped. bootstrap.css:1122:15
Expected end of value but found '\9 '.  Error in parsing value for 'margin-top'.  Declaration dropped. bootstrap.css:2522:18
Expected color but found 'auto'.  Expected color but found '-webkit-focus-ring-color'.  Expected end of value but found '-webkit-focus-ring-color'.  Error in parsing value for 'outline'.  Declaration dropped. bootstrap.css:2540:15
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. bootstrap.css:2578:14
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. bootstrap.css:2581:15
Expected media feature name but found '-webkit-min-device-pixel-ratio'. bootstrap.css:2597:19
Expected end of value but found '\9 '.  Error in parsing value for 'margin-top'.  Declaration dropped. bootstrap.css:2649:18
Unknown property 'touch-action'.  Declaration dropped. bootstrap.css:2994:18
Unknown property 'user-select'.  Declaration dropped. bootstrap.css:3006:13
Expected color but found 'auto'.  Expected color but found '-webkit-focus-ring-color'.  Expected end of value but found '-webkit-focus-ring-color'.  Error in parsing value for 'outline'.  Declaration dropped. bootstrap.css:3015:15
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.css:3037:10
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.css:3496:10
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:5050:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:5051:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:5066:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:5067:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:5074:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:5075:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:5082:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:5083:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:5090:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:5091:20
Unknown property 'zoom'.  Declaration dropped. bootstrap.css:5102:6
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.css:5704:10
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.css:5712:10
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.css:5781:10
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.css:5785:10
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.css:5853:10
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.css:5857:10
Expected media feature name but found 'transform-3d'. bootstrap.css:6087:16
Expected media feature name but found '-webkit-transform-3d'. bootstrap.css:6087:32
Error in parsing value for 'perspective'.  Declaration dropped. bootstrap.css:6095:17
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.css:6154:10
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6161:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6162:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6163:20
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.css:6166:10
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6171:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6172:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6173:20
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.css:6176:10
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.css:6184:10
Expected end of value but found '\9 '.  Error in parsing value for 'background-color'.  Declaration dropped. bootstrap.css:6239:25
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. bootstrap.css:6599:30
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. bootstrap.css:6602:31
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6617:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6618:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6635:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6636:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6645:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6646:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6663:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6664:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6673:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6674:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6691:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6692:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6701:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6702:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6719:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6720:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6729:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6730:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6747:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6748:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6757:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6758:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6775:20
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.css:6776:20
Unknown property 'appearance'.  Declaration dropped. bootstrap.css:6937:12
Error in parsing value for 'padding-right'.  Declaration dropped. bootstrap.css:6939:17
Unknown pseudo-class or pseudo-element '-ms-expand'.  Ruleset ignored due to bad selector. bootstrap.css:6950:8
Unknown property 'appearance'.  Declaration dropped. bootstrap.css:6986:12
Unknown property 'appearance'.  Declaration dropped. bootstrap.css:7059:12
Unknown property '-moz-border-radius'.  Declaration dropped. site.css:33:22
Unknown property '-moz-box-shadow'.  Declaration dropped. site.css:36:19
Unknown property '-moz-border-radius'.  Declaration dropped. site.css:65:22
Expected declaration but found '/'.  Skipped to next declaration. site.css:88:4
Expected media feature name but found 'touch-enabled'. Index:1:8
Expected media feature name but found '-webkit-touch-enabled'. Index:1:24
Expected media feature name but found '-o-touch-enabled'. Index:1:69
Expected media feature name but found '-ms-touch-enabled'. Index:1:88
Expected media feature name but found 'modernizr'. Index:1:108
Unknown property '-moz-opacity'.  Declaration dropped. Index
Error in parsing value for 'background-image'.  Declaration dropped. Index
Expected color but found 'left'.  Error in parsing value for 'background-image'.  Declaration dropped. Index
Error in parsing value for 'background-image'.  Declaration dropped. Index
Error in parsing value for 'background-image'.  Declaration dropped. Index
Error in parsing value for 'background-image'.  Declaration dropped. Index
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery-1.10.2.js:5389:0
"[16:03:15 GMT+0100 (Romance Standard Time)] Browser Link: Failed to invoke return value callback:
SecurityError: The operation is insecure." browserLink:64:552
The Web Console logging API (console.log, console.info, console.warn, console.error) has been disabled by a script on this page.
GET http://localhost:61457/0aa22d3743f24adf985c6663383057f7/arterySignalR/ping [HTTP/1.1 200 OK 15ms]

**Comment by danofa** [comment]
Just an update, i tracked my issue down to the .css file, when i replace the vs2013 generated bootstrap.css with a downloaded bootstrap theme css, the in browser editing and inspecter stops working.

**Comment by RandomlyKnighted** [comment]
I've encountered the same issue. Mine issue also began when I started using a Bootstrap theme I found online.

**Comment by gius** [comment]
This issue is caused by referencing fonts from another location like

    /* in CSS */
    @import url("https://fonts.googleapis.com/css?family=Roboto:400,500");

or

    
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" />

Moreover, this happens only in FF (IE and Chrome are OK and show full BrowserLink, whereas FF shows only Auto-hide checkbox).

Do you have any idea how to fix this?
