### ISSUE TITLE
Create TypeScript Intellisense file from ODatas $metadata

### ISSUE THREAD

**Issue by snebjorn** [madskristensen/WebEssentials2013#1802]
Would be awesome if we could create TypeScript Intellisense files from ODataControllers.

It's already possible to create C# classes from them using this tool: http://blogs.msdn.com/b/odatateam/archive/2014/03/11/how-to-use-odata-client-code-generator-to-generate-client-side-proxy-class.aspx

And while we're at it it would be nice if the generated files when renewed could do a rename on the properties so that the change would refactor the TypeScript files :)

**Comment by am11** [comment]
Since [Roslyn](https://github.com/dotnet/roslyn/) is making strides in VS2015, this feature stand a better chance in [WE 2015](github.com/madskristensen/webEssentials2015). 

BTW, you my want to try out other (much focused) tools such as [TypeScripter](http://cjlpowers.github.io/TypeScripter/) and [TypeLite](http://type.litesolutions.net/) for this C#-TS conversion, which even generate interface definitions from compiled assemblies.

**Comment by snebjorn** [comment]
Thanks, I'll do just that. Also nice tools :)
