### ISSUE TITLE
@import (reference)'d variables are not resolved

### ISSUE THREAD

**Issue by behrangsa** [madskristensen/WebEssentials2013#1861]
After installing the latest version of Web Essentials for Web Essentials 2013, `@import (reference)` declarations are now parsed without producing an error, however variables defined in the referenced less files are not resolved:

![Screenshot](http://i.imgur.com/IoLdM5R.png)

**Comment by robbaman** [comment]
Don't you need to add the .less extension to the import? That's how I always do it and that seems to work.

**Comment by behrangsa** [comment]
@robbaman, the `.less` extension is optional. In our project we are omitting it.

**Comment by rjgotten** [comment]
Intellisense (autocompletion, code correctness hinting) for Less files comes from Visual Studio itself. The preview window and the compiler come from WebEssentials.

The preview window and the backing compiler were updated with WebEssentials to understand the `@import (reference)` syntax. The Intellisense part baked into Visual Studio wasn't.

With a fast-moving language target like Less, it was a *collosal* mistake on Microsoft's part to bake the intellisense into the Web Tools package instead of putting it into a separate package that could be rev-ed on a faster cycle...

**Comment by madskristensen** [comment]
This is an issue with VS2013 and not with Web Essentials. The issue has been fixed in VS2015
