### ISSUE TITLE
LESS compiled CSS relative url paths off by one

### ISSUE THREAD

**Issue by chrisdrobison** [madskristensen/WebEssentials2013#1922]
I have a custom output directory set for LESS compilation. We put a css folder into the folder that contains the less file. I've noticed with the update that all relative paths in the CSS are from the LESS file location rather than the CSS file location. In our case, the CSS output should be showing:

../../picture.png

And are instead:

../picture.png

**Comment by am11** [comment]
Hello @chrisdrobison, there are many factors in play. We have configured Less service as per the documentation for latest version of less (https://github.com/less/less.js) and made sure our existing relative path related tests are passing in compilation scenarios.

Are you using latest released version of WE2013 (v2.6.12)?

In order for us to replicate this issue locally and fix it, we need detailed steps to repro (quickest way is to share a sample project with related files) as per the bug reporting guidelines: https://github.com/madskristensen/WebEssentials2013/blob/master/CONTRIBUTING.md#bug-reports.

**Comment by miksh7** [comment]
I have similar issue after upgrade.
WE options:
- Adjust relative path = true
- Custom output directory = ../

File structure:
Content/Images:
- foo.png

Content/Css/Less/App:
layout.less:
.foo { background-image: url(../../../images/foo.png); }

Content/Css/Less:
base.less
@import "./app/_layout";

WE generates file base.css in Content/Css with
.foo { background-image: url(../../images/foo.png); }

but MUST be 
.foo { background-image: url(../images/foo.png); }

**Comment by am11** [comment]
Thanks @miksh7 for the steps to repro. I forgot to incorporate the changes after this discussion: less/less.js#2084.

Fixed by 84100884 via #1928.

Temporary workaround:

* Open WE2013's installed directory: [see where](https://github.com/madskristensen/WebEssentials2013/issues/1914#issuecomment-125282386).

* In <WE-installed-dir>\Resources\nodejs\tools\server\services\srv-less.js, add the following after line 34:

```javascript
rootpath: path.dirname(path.relative(path.dirname(params.targetFileName), params.sourceFileName)).replace(/\\/g, '/') + "/",
```

If your VS is already running, open PowerShell and execute:

```powershell
stop-process -name node
```

If not, open VS and try saving that less file. :)

About the tests, I need to revisit our unit tests covering Less and friends (someday :soon: &trade;)

**Comment by miksh7** [comment]
Thank you. I did as you described but this update has NOT fixed the issue.

**Comment by chrisdrobison** [comment]
The change worked for me.

**Comment by chrisdrobison** [comment]
I take that back. Looking into it more, it is correct and working completely for me.

**Comment by miksh7** [comment]
Unfortunately, both the workaround above and the new version 2.6.36 has NOT fixed the issue with relative path. Please double check.
Btw, in my case the Custom output directory is set in the solution settings.
