### ISSUE TITLE
css `content:` is manipulated when minified.

### ISSUE THREAD

**Issue by blowsie** [madskristensen/WebEssentials2013#616]
The minifier now changes

This:

```
.fa-cog:before {
  content: "\f013";
}
```

To this:

```
.fa-cog:before{content:""}
```

This effects libraries such as font-awesome, bootsrap and of course any other code using the same technique.

**Comment by j2jensen** [comment]
We recently had this issue crop up in an environment using the Sophos XG WAF: the little tofu box in the font CSS file was getting translated into ASCII characters somewhere between the static file on the server and the browser. [The fix](https://github.com/madskristensen/WebEssentials2013/issues/616#issuecomment-34213765) mentioned above worked to fix it. It's weird, because there's actually no difference in the response headers or anything (they always showed `text/css;charset=utf-8` as the encoding type), but somehow re-mapping the mime type made it respect the encoding when the file got sent across the wire.
